
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "meu-email2@teste.com",
  "password": "senha123",
  "password_confirmation": "senha123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "meu-email@teste.com",
  "password": "senha123"
}

###

GET http://localhost:3000/test_login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc3NDg1fQ.4VbuRE9-nHF6MGTatdottkrjezoyzYsJGFkkzA6-lHI


###

POST http://localhost:3000/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc3NDg1fQ.4VbuRE9-nHF6MGTatdottkrjezoyzYsJGFkkzA6-lHI
Content-Type: application/json

{
  "material": {
    "type": "Book",
    "author_id": 1,
    "author_type": "Person",
    "status": "archived",
    "title": "1984",
    "description": "A dystopian novel by George Orwell.",
    "page_count": 328,
    "isbn": "0123456789002"
  }
}

###

GET http://localhost:3000/materials?page=4

###

GET http://localhost:3000/materials/search?query=19

###

PATCH http://localhost:3000/materials/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc2Mjk1fQ.D3dz73u_TJwGDJl9Su5Gr-MkMEtYnCGKi0h_0Rli9mc
Content-Type: application/json

{
  "material": {
    "status": "published"
  }
}

###

DELETE http://localhost:3000/materials/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc2Mjk1fQ.D3dz73u_TJwGDJl9Su5Gr-MkMEtYnCGKi0h_0Rli9mc

###

POST http://localhost:3000/people
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc3NDg1fQ.4VbuRE9-nHF6MGTatdottkrjezoyzYsJGFkkzA6-lHI
Content-Type: application/json

{
  "person": {
    "name": "Agatha Christie",
    "date_of_birth": "1890-09-15"
  }
}

###

GET http://localhost:3000/people/1

###

POST http://localhost:3000/institutions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc3NDg1fQ.4VbuRE9-nHF6MGTatdottkrjezoyzYsJGFkkzA6-lHI
Content-Type: application/json

{
  "institution": {
    "name": "City Library",
    "city": "Metropolis"
  }
}

###

GET http://localhost:3000/institutions/1