
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "meu-email2@teste.com",
  "password": "senha123",
  "password_confirmation": "senha123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "meu-email@teste.com",
  "password": "senha123"
}

###

GET http://localhost:3000/test_login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDUyNjg4fQ.JQbviTtfn5JfqjZLCgD5rlnvPc7jQBGdUscJV75a_xg

###

GET https://openlibrary.org/isbn/0451526538.json


###

POST http://localhost:3000/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNzYxMDczNjgzfQ.-uavADqnZZqDqlKLg5-5giW_6WiAc3VN-JqNjuuzGOU
Content-Type: application/json

{
  "material": {
    "type": "Book",
    "author_id": 1,
    "author_type": "Person",
    "status": "archived",
    "title": "1984",
    "description": "A dystopian novel by George Orwell.",
    "page_count": 328,
    "isbn": "0123456789012"
  }
}

###

GET http://localhost:3000/materials/1

###

GET http://localhost:3000/materials/search?query=19

###

PATCH http://localhost:3000/materials/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc2Mjk1fQ.D3dz73u_TJwGDJl9Su5Gr-MkMEtYnCGKi0h_0Rli9mc
Content-Type: application/json

{
  "material": {
    "status": "published"
  }
}

###

DELETE http://localhost:3000/materials/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc2Mjk1fQ.D3dz73u_TJwGDJl9Su5Gr-MkMEtYnCGKi0h_0Rli9mc
