POST http://localhost:3000/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDk4Mzk0fQ.u7da66akd_fF1Sah8bexqMZTh5wdEU1o9GX6YAuN7eo
Content-Type: application/json

{
  "material": {
    "type": "Book",
    "author_id": 1,
    "author_type": "Person",
    "status": "done",
    "title": "1984",
    "description": "A dystopian novel by George Orwell.",
    "page_count": 328,
    "isbn": "0123456789002"
  }
}

###

POST http://localhost:3000/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDk4Mzk0fQ.u7da66akd_fF1Sah8bexqMZTh5wdEU1o9GX6YAuN7eo
Content-Type: application/json

{
  "material": {
    "type": "Article",
    "author_id": 2,
    "author_type": "Institution",
    "status": "published",
    "title": "How AI is Changing the World",
    "description": "An article the impacts of artificial intelligence.",
    "doi": "10.1000/183"
  }
}

###

POST http://localhost:3000/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc3NDg1fQ.4VbuRE9-nHF6MGTatdottkrjezoyzYsJGFkkzA6-lHI
Content-Type: application/json

{
  "material": {
    "type": "Video",
    "author_id": 2,
    "author_type": "Institution",
    "status": "published",
    "title": "Advances in AI Research",
    "description": "An article discussing recent advancements in artificial intelligence.",
    "duration_in_minutes": 45
  }
}

###

GET http://localhost:3000/materials

###

GET http://localhost:3000/materials/search

###

PATCH http://localhost:3000/materials/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMTYxMjk1fQ.TPGIczBFWvRhy3ziGrVqfDKxI2GbabIGXtxRk_NHqXE
Content-Type: application/json

{
  "material": {
    "status": "draft"
  }
}

###

DELETE http://localhost:3000/materials/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMDc2Mjk1fQ.D3dz73u_TJwGDJl9Su5Gr-MkMEtYnCGKi0h_0Rli9mc


###

PATCH http://localhost:3000/materials/1/push_status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMTYxMjk1fQ.TPGIczBFWvRhy3ziGrVqfDKxI2GbabIGXtxRk_NHqXE

###

PATCH http://localhost:3000/materials/1/pull_status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNzYxMTYxMjk1fQ.TPGIczBFWvRhy3ziGrVqfDKxI2GbabIGXtxRk_NHqXE